### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by not7cd** [fcc-3city/gd-wody#2]
Ponieważ jestem zielonką, a chcę zacząć coś robić, nie wiem jak podzielić naszą pracę na foldery.
Równie dobrze można podzielić frontend i backend na dwa foldery/obozy ale też jak widzimy późniejszą integrację?
Nie budowałem RESTowych aplikacji.

**Comment by szmelc** [comment]
Możemy spróbować. Myślę że każdy zrobi swoje, a potem na spotkaniu zintegrujemy kod.

**Comment by olo2552** [comment]
Nie lepiej rozbić na front i back repo? Jedno z drugim nie powinno mieć nic wspólnego w sumie, a będą mogły być potem niepotrzebne konflikty przy mergeowaniu.

**Comment by not7cd** [comment]
Jesteś w stanie zainicjalizować express z jasmine? Postaram się dokończyć swój szkic API
